-- =====================================================================
-- Query 4: Executive Group Comparison & Incremental Conversions
-- Description: Synthesizes high-level experiment metrics, baseline conversion,
--              absolute and relative lift, and total incremental conversions
--              directly attributable to the ad campaign.
-- Database: SQLite (campaign_results)
-- =====================================================================

WITH summary AS (
    SELECT 
        test_group,
        COUNT(user_id) AS user_count,
        SUM(converted) AS conversions,
        1.0 * SUM(converted) / COUNT(user_id) AS conversion_rate,
        AVG(total_ads) AS avg_ads_per_user
    FROM campaign_results
    GROUP BY test_group
),
calc AS (
    SELECT 
        MAX(CASE WHEN test_group = 'ad' THEN user_count END) AS n_treatment,
        MAX(CASE WHEN test_group = 'ad' THEN conversions END) AS conv_treatment,
        MAX(CASE WHEN test_group = 'ad' THEN conversion_rate END) AS cr_treatment,
        MAX(CASE WHEN test_group = 'ad' THEN avg_ads_per_user END) AS ads_treatment,
        MAX(CASE WHEN test_group = 'psa' THEN user_count END) AS n_control,
        MAX(CASE WHEN test_group = 'psa' THEN conversions END) AS conv_control,
        MAX(CASE WHEN test_group = 'psa' THEN conversion_rate END) AS cr_control,
        MAX(CASE WHEN test_group = 'psa' THEN avg_ads_per_user END) AS ads_control
    FROM summary
)
SELECT 
    n_treatment AS treatment_users,
    n_control AS control_users,
    n_treatment + n_control AS total_users,
    ROUND(100.0 * n_treatment / (n_treatment + n_control), 2) AS treatment_share_pct,
    conv_treatment AS treatment_conversions,
    conv_control AS control_conversions,
    ROUND(cr_treatment * 100.0, 4) AS treatment_cr_pct,
    ROUND(cr_control * 100.0, 4) AS control_cr_pct,
    ROUND((cr_treatment - cr_control) * 100.0, 4) AS absolute_lift_pct_pts,
    ROUND(((cr_treatment - cr_control) / cr_control) * 100.0, 2) AS relative_lift_pct,
    ROUND(ads_treatment, 2) AS avg_ads_treatment,
    ROUND(ads_control, 2) AS avg_ads_control,
    -- Expected baseline conversions if treatment had seen PSA:
    ROUND(n_treatment * cr_control, 0) AS expected_baseline_conversions,
    -- Actual incremental conversions generated by the campaign:
    ROUND(conv_treatment - (n_treatment * cr_control), 0) AS incremental_conversions
FROM calc;
